//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gabriel.Cat.Google {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gabriel.Cat.Google.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;HTML&gt;  
        ///    &lt;Head&gt;  
        ///        &lt;script src=&quot;jquery.js&quot; temp_src=&quot;jquery.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;  
        ///        &lt;script language=&quot;javascript&quot; type=&quot;text/javascript&quot;&gt;  
        ///    var OAUTHURL = &apos;https://accounts.google.com/o/oauth2/auth?&apos;;  
        ///    var VALIDURL = &apos;https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=&apos;;  
        ///    var SCOPE = &apos;https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email&apos;;  
        ///    var CLIENTID = &apos;#ClientId#&apos;;  
        ///    var REDIRECT = &apos;#UrlRe [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string htmlPaginaBasicaLoginGooglePlus {
            get {
                return ResourceManager.GetString("htmlPaginaBasicaLoginGooglePlus", resourceCulture);
            }
        }
    }
}
